---
title: "El sistema de creditos en la educación superior: Endeudar para educar"
format: html
editor: visual
bibliography: TrabajoInvestigacion.bib
link-citations: true
autor: Golam Berlagoscky Mayorga
---

## Introducción

La promesa de una movilidad social en el ingreso a la educación superior en Chile es una premisa que, dentro de las lógicas familiares para lograr un ascenso social se muestra como una gran oportunidad con una buena proyección a futuro en el mercado laboral, la esperanza por una oprtunidad de un mejor futuro configura un horizonte al cual son los jóvenes de las familias quienes tienen el llamado de intentarlo, estableciendo de esta forma, una determinada manera de construir formas de ingreso y acceso a la educación superior.

El endeudamiento como un sistema de financiamiento de la educación aparece como un apéndice de un sistema neoliberal que ha hecho del Estado un aparato a favor del mercado que ha vuelto clientes a los individuos por medio de un intervencionismo, en función de un sistema que promete movilidad social a costa de una deuda mucho mayor de las expectativas de mejoras que la propia educación superior promete, como lo expone en su estudio de gubernamentalidad @lorenaperez-roaGobernadosPorDeudas2018 referente a un Estado reproductor de deudas en el sistema educacional.

Los factores como el tipo de educación en la que se desarrollan las personas hasta el ingreso a la educación superior trae consigo una serie de temores frente al gran costo que implica el acceso a la educación superior, @vicenteespinozaEstratificacionMovilidadSocial2013 se pregunta por el tipo de carrera estudiada, la deserción de los estudios y la empleabilidad son constantes a la hora de la toma de decisión por entrar a la educación superior, por ende, es señal de una gran inseguridad para los estudios de la estratificación social.

En profundización a esto último se condice con la evidencia de altos grados de correlacion entre estudiantes de enseñanza media de colegios científicos humanistas que son más propensos a estudiar con creditos que estudiantes provenientes de la educación técnica, quienes son más reacios al financiamiento por endeudamiento, como expone @olavarriagambiEndeudamientoEstudiantilAcceso2024. En favor de esto, se complementan con los estudios realizados por @denegricoriaEscalaActitudesHacia2011 quien plantea una escala de actitudes orientadas a los créditos, en la cual se construyen perfiles que guardan relación con el endeudamiento, teniendo como principal hallazgo en la ciudad de Temuco, un 42,4% de los estudiantes con un perfil austero frente al uso de creditos, optando por evitar la deuda y buscar el ahorro.

La relevancia de un estudio de este tipo es que resulta una aproximacion hacia el modelo de educacion de mercado y sus impactos post estudios en los distintos sectores educacionales, de esta manera, el sistema de educación por endeudamiento afectaría de manera desigual tanto a los estudiantes provenientes de la educación técnica, humanista científico y artística, significando una oportunidad para muchos pero un impedimento para muchos otros en la búsqueda de una mejora de la calidad de vida.

A raíz de lo expuesto anteriormente se espera analizar que a una mayor cantidad de financiamento vía créditos o endeudamientos en el acceso a la educación superior incrementa la percepción de desigualdad en los estudiantes, de esta forma acentuando la crisis de un sistema de educación de mercado en Chile.

## Análisis de datos

Los datos producidos durante la realización de esta investigación dan cuenta de un fenómeno mercantil que ha generado importantes cambios en el sistema de educación superior mediante el financiamiento de carreras técnicas y profesionales a través de créditos fiscales, transformando así la educación superior en un sistema de endeudamiento progresivo en el cual los estudiantes deben optar al crédito y a la alta probabilidad de endeudarse al terminar sus estudios para lograr incorporarse en un mercado laboral cada vez más exigente y competitivo.

En primer lugar, mostraré un gráfico de barras que nos adentrará en el panorama estudiantil al interior de la educación superior en Chile.

```{r}
summarytools::dfSummary(casen_superior, plain.ascii = FALSE)

```

Estos primeros datos nos dan una muestra general del financiamiento de los estudiantes de distintos niveles y establecimientos educacionales, del cual la población de estudiantes superiores se ve distribuida en tres niveles educacionales, teniendo como el más frecuente para esta población el nivel profesional con un total de 4.573 casos, seguido por la formación técnica nivel superior con un total de 1.579 estudiantes, mientras que el nivel de posgrado se encuentra con 465 casos.

A su vez, el tipo de establecimiento educacional al que asisten los estudiantes será clave para determinar cuántos estudiantes que se encuentran cursando alguna carrera en estos establecimientos están financiando sus estudios mediante un tipo de crédito. En este aspecto, encontramos que son 2.282 estudiantes que se encuentran cursando carreras en institutos profesionales o centros de formación técnica, mientras que serán 4.209 estudiantes en total los que cursen en establecimientos universitarios, los cuales 3.049 serán de universidades privadas y 1.160 serán de universidades estatales.

Para adentrarnos más en la situación de financiamiento de estas carreras nos preguntamos por cuántos de estos estudiantes, que se encuentran en el sistema de educación superior, pagan el costo de la carrera o si tienen algún beneficio que cubra el 100% del arancel de su carrera, tan solo 1.299 estudiantes no paga el costo completo de su carrera a causa de un beneficio que cubra el 100% del arancel, mientras que es el 80,4% con 5.318 estudiantes en el nivel superior que deben hacerse cargo de una parte del coste de sus estudios al no contar con un beneficio que cubra el 100% del arancel.

Finalmente, la variable más relevante pregunta directamente si dentro del financimiento de su carrera se encuentra con algún crédito, de la cual se despreden 2.669 casos de estudiantes superiores sujetos a esta red de endeudamiento para lograr complementar.
