<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>El sistema de creditos en la educación superior: Endeudar para educar</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="creditosuniversitarios_files/libs/clipboard/clipboard.min.js"></script>
<script src="creditosuniversitarios_files/libs/quarto-html/quarto.js"></script>
<script src="creditosuniversitarios_files/libs/quarto-html/popper.min.js"></script>
<script src="creditosuniversitarios_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="creditosuniversitarios_files/libs/quarto-html/anchor.min.js"></script>
<link href="creditosuniversitarios_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="creditosuniversitarios_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="creditosuniversitarios_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="creditosuniversitarios_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="creditosuniversitarios_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">El sistema de creditos en la educación superior: Endeudar para educar</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>La promesa de una movilidad social en el ingreso a la educación superior en Chile es una premisa que, dentro de las lógicas familiares para lograr un ascenso social se muestra como una gran oportunidad con una buena proyección a futuro en el mercado laboral, la esperanza por una oprtunidad de un mejor futuro configura un horizonte al cual son los jóvenes de las familias quienes tienen el llamado de intentarlo, estableciendo de esta forma, una determinada manera de construir formas de ingreso y acceso a la educación superior.</p>
<p>El endeudamiento como un sistema de financiamiento de la educación aparece como un apéndice de un sistema neoliberal que ha hecho del Estado un aparato a favor del mercado que ha vuelto clientes a los individuos por medio de un intervencionismo, en función de un sistema que promete movilidad social a costa de una deuda mucho mayor de las expectativas de mejoras que la propia educación superior promete, como lo expone en su estudio de gubernamentalidad <span class="citation" data-cites="lorenaperez-roaGobernadosPorDeudas2018">Lorena Pérez-Roa, Lorena Pérez-Roa, and Pérez-Roa (<a href="#ref-lorenaperez-roaGobernadosPorDeudas2018" role="doc-biblioref">2018</a>)</span> referente a un Estado reproductor de deudas en el sistema educacional.</p>
<p>Los factores como el tipo de educación en la que se desarrollan las personas hasta el ingreso a la educación superior trae consigo una serie de temores frente al gran costo que implica el acceso a la educación superior, <span class="citation" data-cites="vicenteespinozaEstratificacionMovilidadSocial2013">Vicente Espinoza et al. (<a href="#ref-vicenteespinozaEstratificacionMovilidadSocial2013" role="doc-biblioref">2013</a>)</span> se pregunta por el tipo de carrera estudiada, la deserción de los estudios y la empleabilidad son constantes a la hora de la toma de decisión por entrar a la educación superior, por ende, es señal de una gran inseguridad para los estudios de la estratificación social.</p>
<p>En profundización a esto último se condice con la evidencia de altos grados de correlacion entre estudiantes de enseñanza media de colegios científicos humanistas que son más propensos a estudiar con creditos que estudiantes provenientes de la educación técnica, quienes son más reacios al financiamiento por endeudamiento, como expone <span class="citation" data-cites="olavarriagambiEndeudamientoEstudiantilAcceso2024">Olavarría Gambi and Allende González (<a href="#ref-olavarriagambiEndeudamientoEstudiantilAcceso2024" role="doc-biblioref">2024</a>)</span>. En favor de esto, se complementan con los estudios realizados por <span class="citation" data-cites="denegricoriaEscalaActitudesHacia2011">Denegri Coria et al. (<a href="#ref-denegricoriaEscalaActitudesHacia2011" role="doc-biblioref">2011</a>)</span> quien plantea una escala de actitudes orientadas a los créditos, en la cual se construyen perfiles que guardan relación con el endeudamiento, teniendo como principal hallazgo en la ciudad de Temuco, un 42,4% de los estudiantes con un perfil austero frente al uso de creditos, optando por evitar la deuda y buscar el ahorro.</p>
<p>La relevancia de un estudio de este tipo es que resulta una aproximacion hacia el modelo de educacion de mercado y sus impactos post estudios en los distintos sectores educacionales, de esta manera, el sistema de educación por endeudamiento afectaría de manera desigual tanto a los estudiantes provenientes de la educación técnica, humanista científico y artística, significando una oportunidad para muchos pero un impedimento para muchos otros en la búsqueda de una mejora de la calidad de vida.</p>
<p>A raíz de lo expuesto anteriormente se espera analizar que a una mayor cantidad de financiamento vía créditos o endeudamientos en el acceso a la educación superior incrementa la percepción de desigualdad en los estudiantes, de esta forma acentuando la crisis de un sistema de educación de mercado en Chile.</p>
</section>
<section id="análisis-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-datos">Análisis de datos</h2>
<p>Los datos producidos durante la realización de esta investigación dan cuenta de un fenómeno mercantil que ha generado importantes cambios en el sistema de educación superior mediante el financiamiento de carreras técnicas y profesionales a través de créditos fiscales, transformando así la educación superior en un sistema de endeudamiento progresivo en el cual los estudiantes deben optar al crédito y a la alta probabilidad de endeudarse al terminar sus estudios para lograr incorporarse en un mercado laboral cada vez más exigente y competitivo.</p>
<p>En primer lugar, mostraré una tabla que nos adentrará en el panorama estudiantil al interior de la educación superior en Chile. Para esto abriré la base de datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"C:/Users/franr/OneDrive/Documentos/GitHub/Trabajo-R-Uah/Processing/Procesamiento Trabajo Creditos Universitarios.Rdata"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Realizamos una instalación de paquetes a utilizar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>               dplyr, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>              stargazer, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>              sjmisc, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>              summarytools, </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>              kableExtra, </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>              sjPlot, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>              corrplot,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>              sessioninfo, </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>              ggplot2) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(casen_superior, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>### Data Frame Summary  
#### casen_superior  
**Dimensions:** 6617 x 4  
**Duplicates:** 6575  

------------------------------------------------------------------------------------------------------------------------------------
No   Variable        Label                             Stats / Values   Freqs (% of Valid)   Graph              Valid      Missing  
---- --------------- --------------------------------- ---------------- -------------------- ------------------ ---------- ---------
1    credi_sup\      Tipo de crédito                   1\. 0\           3948 (59.7%)\        IIIIIIIIIII \      6617\      0\       
     [factor]                                          2\. 1            2669 (40.3%)         IIIIIIII           (100.0%)   (0.0%)   

2    nivel_educ\     Nivel educacional                 1\. 2\           1579 (23.9%)\        IIII \             6617\      0\       
     [factor]                                          2\. 3\           4573 (69.1%)\        IIIIIIIIIIIII \    (100.0%)   (0.0%)   
                                                       3\. 4            465 ( 7.0%)          I                                      

3    pago_carrera\   Paga por la carrera que estudia   1\. 0\           1299 (19.6%)\        III \              6617\      0\       
     [factor]                                          2\. 1            5318 (80.4%)         IIIIIIIIIIIIIIII   (100.0%)   (0.0%)   

4    estab_sup\      Tipo de establecimiento           1\. 2\           2282 (34.5%)\        IIIIII \           6617\      0\       
     [factor]                                          2\. 3\           3049 (46.1%)\        IIIIIIIII \        (100.0%)   (0.0%)   
                                                       3\. 4\           1160 (17.5%)\        III \                                  
                                                       4\. 5            126 ( 1.9%)                                                 
------------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(casen_superior, <span class="at">headings=</span><span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Switching method to 'browser'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Output file written: C:\Users\franr\AppData\Local\Temp\RtmpOAuvab\file47c4d16cda.html</code></pre>
</div>
</div>
<p>Estos primeros datos nos dan una muestra general del financiamiento de los estudiantes de distintos niveles y establecimientos educacionales, del cual la población de estudiantes superiores se ve distribuida en tres niveles educacionales, teniendo como el más frecuente para esta población el nivel profesional con un total de 4.573 casos, seguido por la formación técnica nivel superior con un total de 1.579 estudiantes, mientras que el nivel de posgrado se encuentra con 465 casos.</p>
<p>A su vez, el tipo de establecimiento educacional al que asisten los estudiantes será clave para determinar cuántos estudiantes que se encuentran cursando alguna carrera en estos establecimientos están financiando sus estudios mediante un tipo de crédito. En este aspecto, encontramos que son 2.282 estudiantes que se encuentran cursando carreras en institutos profesionales o centros de formación técnica, mientras que serán 4.209 estudiantes en total los que cursen en establecimientos universitarios, los cuales 3.049 serán de universidades privadas y 1.160 serán de universidades estatales.</p>
<p>Para adentrarnos más en la situación de financiamiento de estas carreras nos preguntamos por cuántos de estos estudiantes, que se encuentran en el sistema de educación superior, pagan el costo de la carrera o si tienen algún beneficio que cubra el 100% del arancel de su carrera, tan solo 1.299 estudiantes no paga el costo completo de su carrera a causa de un beneficio que cubra el 100% del arancel, mientras que es el 80,4% con 5.318 estudiantes en el nivel superior que deben hacerse cargo de una parte del coste de sus estudios al no contar con un beneficio que cubra el 100% del arancel.</p>
<p>Finalmente, la variable más relevante pregunta directamente si dentro del financimiento de su carrera se encuentra con algún crédito, de la cual se despreden 2.669 casos de estudiantes superiores sujetos a esta red de endeudamiento para lograr complementar.</p>
<p>Ahora pasaremos a observar las medidas de tendencia central de las variables para su posterior análisis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(casen_superior,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 14%">
<col style="width: 36%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">credi_sup</td>
<td style="text-align: left;">Tipo de crédito</td>
<td style="text-align: right;">6617</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.4033550</td>
<td style="text-align: right;">0.4906079</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">nivel_educ</td>
<td style="text-align: left;">Nivel educacional</td>
<td style="text-align: right;">6617</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.8316458</td>
<td style="text-align: right;">0.5297174</td>
<td style="text-align: left;">2 (2-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">pago_carrera</td>
<td style="text-align: left;">Paga por la carrera que estudia</td>
<td style="text-align: right;">6617</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.8036875</td>
<td style="text-align: right;">0.3972377</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">estab_sup</td>
<td style="text-align: left;">Tipo de establecimiento</td>
<td style="text-align: right;">6617</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.8685205</td>
<td style="text-align: right;">0.7610147</td>
<td style="text-align: left;">3 (2-5)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En esta sección podemos observar que las medidas de tendencia central que se desprenden de la primera variable sobre el tipo de credito (credi_sup) evidencian una media de 0.403 entre los valores del 0 al 1, en donde 1 es el uso de algun tipo de credito para el financiamiento de su carrera en la educación superior, lo que significa que existe una proporción de al menos un 40% de estudiantes que se encuentran en una situación crediticia con alguna institución financiera, por su parte la desviación estándar se mantiene con un total de 0.490 lo que representa una dispersión de casi 0.5 puntos de desviación de los datos con respecto a la media.</p>
<p>La siguiente variable a describir es el Nivel educacional que responden a una media 2,831 en donde el valor que toma la categoría “2” es la de “Técnico nivel superior” lo que demuestra una preponderante cantidad de estudiantes que se encuentran en este nivel educacional, mientras que su desviación estándar responde al valor de 0.529 lo que representa una gran dispersión de los datos con respecto a su media.</p>
<p>La tercera variable sobre el pago por la carrera encuentra su media en 0.803 lo que representa una gran concentración de los datos en la categoría de “Sí, paga el arancel por la carrera que estudia” que recibe un valor de 1 y con una dispersión baja de 0.397 en cuanto a su desviación estándar se demuestra una gran concentración de estudiantes superiores que deben hacerse cargo de costear sus estudios sin un beneficio que cubra el 100% de su educación.</p>
<p>Por último, la cuarta variable sobre el tipo de establecimiento al que asiste aquel estudiante de educación superior dispone de una media de 2,868 en una escala de categorías que ven desde universidades hasta centros de formación técnica e institutos profesionales, en este caso el promedio de esta variable representaría que existe una presencia importante, en esta base de datos, de estudiantes superiores de universidades privadas y tecnicos profesionales. La desviación estándar de 0.761 nos indicaría una importante dispersión de los datos distribuidos a lo largo de estas categorías, definiendo casos muy extremos como “otros” que representan estudios en el extranjero y academias militares.</p>
<p>Para que la investigación adquiera una mayor profunidad, se realizará la construcción de gráficos que permitan el análisis sustantivo mediante el cruce de la infromación que proporcionan las variables seleccionadas. En primer lugar, encuentro que el cruce entre la variable de establecimientos educacionales superiores y el uso de algún tipo de crédito resultaría útil para encontrar una asociación entre el tipo de establecimiento al que se accede y la necesidad de optar por un crédito para complementar el pago de aranceles.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>casen_superior <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estab_sup, <span class="at">fill =</span> credi_sup)) <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Establecimiento Educacional Superior"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>) <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">"Estudiantes con créditos universitarios"</span>)<span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Algun tipo de crédito'</span>,<span class="st">'Sin crédito'</span>)) <span class="sc">+</span> </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">color =</span> <span class="st">"black"</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">angle =</span> <span class="dv">35</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="creditosuniversitarios_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Desde este gráfico podemos encontrar que los establecimientos de educación superior en Chile que tienen más estudiantes con situación de créditos es la educación técnica profesional constituida por los instituos profesionales y centros de formación técnica con más de la mitad de los estudiantes de estos establecimientos educacionales se encuentran con créditos para costear sus estudios superiores.</p>
<p>Para la situación de los estudiantes universitarios resulta pareja la proporción entre estudiantes que tienen algún beneficio que cubra la totalidad de sus aranceles versus aquella mitad que necesita y se encuentra estudiando con créditos. Aún así se observa una mayor cantidad de estudiantes con situación crediticia en comparación con aquellos estudiantes que no dependen de las deudas para la continuidad de sus estudios.</p>
<p>La siguiente descripción expondrá el último hallazgo extraído a partir de esta investigación y la selección de las variables,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>casen_superior <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> nivel_educ, <span class="at">fill =</span> pago_carrera)) <span class="sc">+</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Nivel Educacional"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>) <span class="sc">+</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">"Estudiantes que pagan sus estudios"</span>)<span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'No lo paga'</span>,<span class="st">'Si lo paga'</span>)) <span class="sc">+</span> </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">color =</span> <span class="st">"black"</span>),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">angle =</span> <span class="dv">35</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="creditosuniversitarios_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En este gráfico nos encontramos con estudiantes de educación superior que se deben hacer cargo del pago de sus estudios superiores, representando que la gran mayoría de los estudiantes, independiente del nivel educacional que tengan se terminan por hacer cargo de los aranceles que sus respectivas ccarreras dispongan.</p>
<p>En primera instancia, con el valor “2” observamos a los técnicos nivel superior que declaran haber pagado parte de su arancel, sin reconocer un beneficio que se haga cargo de la totalidad del arancel, por otro lado la mayoría de los profesionales con el valor “3” habrían declarado hacerse cargo del costo de sus estudios y finalmente, quienes estudiaron posgrados (con el valor “4”) en algun establecimiento de educación superior declaran con gran mayoría haberse hecho cargo de los costos de sus estudios.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-denegricoriaEscalaActitudesHacia2011" class="csl-entry" role="listitem">
Denegri Coria, Marianela, Daniel Cabezas Gaete, Carlos Del Valle Rojas, Yessica González Gómez, and Jocelyne Sepúlveda Aravena. 2011. <span>“Escala de <span>Actitudes</span> Hacia El <span>Endeudamiento</span>: Validez Factorial y Perfiles Actitudinales En Estudiantes Universitarios Chilenos.”</span> <em>Universitas Psychologica</em> 11 (2): 497–509. <a href="https://doi.org/10.11144/Javeriana.upsy11-2.eaev">https://doi.org/10.11144/Javeriana.upsy11-2.eaev</a>.
</div>
<div id="ref-lorenaperez-roaGobernadosPorDeudas2018" class="csl-entry" role="listitem">
Lorena Pérez-Roa, Lorena Pérez-Roa, and Lorena Pérez-Roa. 2018. <span>“Gobernados Por Las Deudas <span>El</span> Caso de Los j<span>ó</span>venes Adultos Deudores de Los Cr<span>é</span>ditos <span>Corfo</span> de <span>Santiago</span> de <span>Chile</span>.”</span> <em>ARQ</em> 31 (2): 455–66. <a href="https://doi.org/10.5209/cuts.54593">https://doi.org/10.5209/cuts.54593</a>.
</div>
<div id="ref-olavarriagambiEndeudamientoEstudiantilAcceso2024" class="csl-entry" role="listitem">
Olavarría Gambi, Mauricio, and Claudio Allende González. 2024. <span>“Endeudamiento Estudiantil y Acceso a La Eduaci<span>ó</span>n Superior En <span>Chile</span>.”</span> <em>Revista Espa<span>ñ</span>ola de Investigaciones Sociol<span>ó</span>gicas</em>, no. 141 (February): 91–112. <a href="https://doi.org/10.5477/cis/reis.141.91">https://doi.org/10.5477/cis/reis.141.91</a>.
</div>
<div id="ref-vicenteespinozaEstratificacionMovilidadSocial2013" class="csl-entry" role="listitem">
Vicente Espinoza, Vicente Espinoza, Émmanuelle Barozet, Emmanuelle Barozet, María Luisa Hevia Méndez, and María Luisa Méndez. 2013. <span>“Estratificaci<span>ó</span>n y Movilidad Social Bajo Un Modelo Neoliberal: <span>El</span> Caso de <span>Chile</span>,”</span> no. 25 (May): 169–91.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>